### ISSUE TITLE
secrets-init fails if google root CA is not installed

### ISSUE THREAD

**Issue by jonatiao** [doitintl/secrets-init#15]
Hello,
I'm using busybox and secrets-init 0.4.0 fails if google root CA is not available.

`/ # /tmp/bin/secrets-init --provider google env
ERRO[0000] failed to resolve secrets                     error="failed to get secret from Google Secret Manager: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority\""`

I'm sure if this is by design or if secrets-init should come with a pre-installed CA somehow.

Could you please also document it, maybe in the document below as well in the READM.md?
https://blog.doit-intl.com/kubernetes-and-secrets-management-in-cloud-858533c20dca

Thx!

**Comment by michaelniemand** [comment]
experiencing the same issue, so +1

**Comment by michaelniemand** [comment]
Did you ever find a workaround @jonatiao ?

**Comment by jonatiao** [comment]
Hello Michael,

There are some ways do fix that:
https://stackoverflow.com/questions/45388934/how-do-i-make-an-https-call-in-a-busybox-docker-container-running-go

in our case we used the image https://hub.docker.com/r/odise/busybox-curl

**Comment by michaelniemand** [comment]
thanks for the reply @jonatiao it is highly appreciated! I went with https://external-secrets.io/ instead
