### ISSUE TITLE
Sometimes I get a "ERRO[0000] failed to send system signal to the process"

### ISSUE THREAD

**Issue by jonatiao** [doitintl/secrets-init#16]
secrets-init:0.4.0

Sometimes, I don't know why, I get these errors:
`kubectl exec  --stdin --tty mypod-init -- /bin/ash
Defaulted container "mypod-cm" out of: mypod-cm, writefile (init)
/ # /tmp/bin/secrets-init --provider google env
`
`GOOGLE_APPLICATION_CREDENTIALS=/credential/credentials.json`
`PASS=It worked!`
`ERRO[0000] failed to send system signal to the process   args="[env]" error="no such process" path=/usr/bin/env pid=23 signal=SIGURG`

secrets-init is doing its job, the PASS was translated. Still, I get the error below sometimes, pretty rare, but it happens.

ERRO[0000] failed to send system signal to the process   args="[env]" error="no such process" path=/usr/bin/env pid=23 signal=SIGURG

**Comment by ghost** [comment]
got the same issue. 
Has anyone have a hint on this one ?

**Comment by alexei-led** [comment]
@jonatiao can you attach Pod yaml and commands to reproduce the problem?

**Comment by jonatiao** [comment]
Oh. I'm not working anymore for the company I implemented a solution based on secrets-init. Still, I have the deployment manifest template.. but I cannot simulate it anymore since I'm not there.

[deployment-with-gcp_svc_account.txt](https://github.com/doitintl/secrets-init/files/9929568/deployment-with-gcp_svc_account.txt)

ps. Can´t attach yaml files. So here it goes as .txt, please rename it.
