### ISSUE TITLE
Option to exit early on error

### ISSUE THREAD

**Issue by evandam** [doitintl/secrets-init#21]
Hey @alexei-led 

Thanks for the project, it's really helpful!

I was wondering if it's possible to have an option/flag to exit non-zero if a secret can't be found/accessed instead of warning and still running the child process? It would be much quicker to debug issues with bad secrets if this can be done.

Thanks in advance!

**Comment by scalp42** [comment]
Same issue here 😅

**Comment by alexei-led** [comment]
I can review the PR
