### ISSUE TITLE
secrets-init does not overwrite existing empty environment variables

### ISSUE THREAD

**Issue by evandam** [doitintl/secrets-init#23]
Hey @alexei-led thanks for the project. I noticed confusing behavior that secrets-init doesn't set an environment variable if it already exists as an empty value. Can this behavior be changed or be configurable? Our scenario is that we have default values in our environment but want to overwrite if they have a matching secret in Secrets Manager.

Thanks!

**Comment by alexei-led** [comment]
@evandam would you like to contribute a PR?

**Comment by evandam** [comment]
I would love to, but alas I don't write Go 😅 

It's not a blocker or anything for us, but something to be aware of. Appreciate your work on the project!

**Comment by alexei-led** [comment]
Unfortunately this is the way Go `cmd.Env` works
