### ISSUE TITLE
Do any secrets get stored within a layer of the docker image?

### ISSUE THREAD

**Issue by sephethus** [doitintl/secrets-init#24]
How does secrets-init avoid storing secrets inside the image?

**Comment by jonatiao** [comment]
Hello,

You mean the container, right? Because the image is static. I mean secrets-init does not need any secrets inside the image.

"secrets-init also passes almost all environment variables without modification, replacing secret variables with values from secret management services."

Goinjg further. You provide an **endpoint** as a secret address, not a secret.

**Comment by sephethus** [comment]
Ah I think I figured out how this works, I was thinking it was something to be added as a part of a container image and not as a sidecar in a pod. Am I getting this right? I'm trying to deploy this in GKE via helm and it's trying to load as one of 3 containers in the deployment and I keep getting errors about the mount path. I'll post it in another issue.

**Comment by jonatiao** [comment]
Depends on your use case.
In my case I was using the secrets-init binary as well GCP's secret manager. GKE too.
When you create the secret, GCP will give you a API path. Like:
MY_DB_PASSWORD=gcp:secretmanager:projects/myproject/secrets/my_secret_name_in_gcps_secret_manager

Then you change your POD or DEPLOYMENT manifest to include the variable which will hold the API path.You can do this in several ways.. so it's up to you(for instance store the path in a configmap and mount it as var env)
Then you change your dockerfile CMD or ENTRYPOINT to call secrets-init first. Like this:

CMD /tmp/bin/secrets-init --provider google java -jar mysoftware.jar

I mean, there are many ways to do this.

**Comment by alexei-led** [comment]
@sephethus no secrets are stored inside the container. The `secrets-init` binary injects referenced secrets as environment variables to the child process. These variables are not persisted.
