### ISSUE TITLE
Support for Oracle Cloud Vault

### ISSUE THREAD

**Issue by herberthnilsen** [doitintl/secrets-init#37]
Hi,

I work at Oracle and a customer is using this component, I clone your repo and make an update to support Oracle Cloud Vault

please, check it out and when possible include this directly on your repo.

I don't know Go Lang, so I don't create the files to test the solution and I comment a lot of lint that was on Makefile just to build the container, 

The solution is working to Oracle Cloud Vault, but don't have automated test files.

Checkout on my git

https://github.com/herberthnilsen/secrets-init
https://github.com/herberthnilsen/kube-secrets-init

**Comment by alexei-led** [comment]
consider submitting a PR with tests and docs
