### ISSUE TITLE
DoIt Binary Fails in Docker Container When Running Locally (Missing Credentials)

### ISSUE THREAD

**Issue by paavanc** [doitintl/secrets-init#5]
This binary fails when running in a docker container locally. The failure occurs because we are not including any gcp credentials locally, as they are only supplied in production.  Can someone augment the code so that there is no segfault if gcp credentials are missing from the container. An example of the docker cmd used is `CMD /usr/local/bin/secrets-init --provider=google <your command>.

**Comment by paavanc** [comment]
we have this pr in place as well: https://github.com/doitintl/secrets-init/pull/6

**Comment by alexei-led** [comment]
Fixed with PR #6
