### ISSUE TITLE
failed to get secret from AWS Secrets Manager: MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by cheddarwhizzy** [doitintl/secrets-init#9]
If you don't specify AWS_REGION environment variable, you won't be able to fetch an ASM secret. This could be pulled from the ARN of the secret

**Comment by scalp42** [comment]
Jumping on this, definitely would be great.

**Comment by alexei-led** [comment]
@cheddarwhizzy can you submit a PR?
